### Build stage 0
FROM registry.datahub.tgw-group.cloud/docker-hub-proxy/python:3.13.3-bookworm AS debian

### erlang and rebar3
ENV OTP_VERSION="27.3.4" \
    REBAR3_VERSION="3.24.0"

LABEL org.opencontainers.image.version=$OTP_VERSION

RUN set -xe \
	&& OTP_DOWNLOAD_URL="https://github.com/erlang/otp/releases/download/OTP-${OTP_VERSION}/otp_src_${OTP_VERSION}.tar.gz" \
	&& OTP_DOWNLOAD_SHA256="c3a0a0b51df08f877eed88378f3d2da7026a75b8559803bd78071bb47cd4783b" \
	&& CONFIGURE_ARGS="--without-wx --without-debugger --without-observer --without-et --without-javac --without-odbc --without-megaco" \
	&& fetchDeps=' \
		curl \
		ca-certificates' \
	&& apt-get update \
	&& apt-get install -y --no-install-recommends $fetchDeps \
	&& curl -fSL -o otp-src.tar.gz "$OTP_DOWNLOAD_URL" \
	&& echo "$OTP_DOWNLOAD_SHA256  otp-src.tar.gz" | sha256sum -c - \
	&& runtimeDeps=' \
		libodbc1 \
		libsctp1 \
	' \
	&& buildDeps=' \
		autoconf \
		dpkg-dev \
		gcc \
		g++ \
		make \
		libncurses-dev \
		unixodbc-dev \
		libsctp-dev \
	' \
	&& apt-get install -y --no-install-recommends $runtimeDeps \
	&& apt-get install -y --no-install-recommends $buildDeps \
	# tell git to use https instead of git protocol (faxe dependencies)
	&& git config --global url."https://".insteadOf git:// \
	&& export ERL_TOP="/usr/src/otp_src_${OTP_VERSION%%@*}" \
	&& mkdir -vp $ERL_TOP \
	&& tar -xzf otp-src.tar.gz -C $ERL_TOP --strip-components=1 \
	&& rm otp-src.tar.gz \
	&& ( cd $ERL_TOP \
	  && gnuArch="$(dpkg-architecture --query DEB_HOST_GNU_TYPE)" \
	  && ./configure --build="$gnuArch" $CONFIGURE_ARGS \
	  && make -j$(nproc) \
	  && make install ) \
	&& find /usr/local -name examples | xargs rm -rf \
	&& REBAR3_DOWNLOAD_URL="https://github.com/erlang/rebar3/archive/${REBAR3_VERSION}.tar.gz" \
	&& REBAR3_DOWNLOAD_SHA256="391b0eaa2825bb427fef1e55a0d166493059175f57a33b00346b84a20398216c" \
	&& mkdir -p /usr/src/rebar3-src \
	&& curl -fSL -o rebar3-src.tar.gz "$REBAR3_DOWNLOAD_URL" \
	&& echo "$REBAR3_DOWNLOAD_SHA256 rebar3-src.tar.gz" | sha256sum -c - \
	&& tar -xzf rebar3-src.tar.gz -C /usr/src/rebar3-src --strip-components=1 \
	&& rm rebar3-src.tar.gz \
	&& cd /usr/src/rebar3-src \
	&& HOME=$PWD ./bootstrap \
	&& install -v ./rebar3 /usr/local/bin/ \
	&& rm -rf /usr/src/rebar3-src \
	&& find /usr/local -name examples | xargs rm -rf \
    && apt-get purge -y --auto-remove $buildDeps $fetchDeps \
    && rm -rf $ERL_TOP /var/lib/apt/lists/*

CMD ["erl"]

### python requirements
COPY python_requirements.txt ./
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ make \
	&& python -m pip install --upgrade pip \
    && pip install --no-cache-dir -r python_requirements.txt \
    && apt-get purge -y --auto-remove gcc g++ make \
    && rm -rf /var/lib/apt/lists/*


### Build stage 1
ARG VERSION=latest
FROM debian AS erlang

# Set working directory
RUN mkdir -p /buildroot/rebar3/bin
WORKDIR /buildroot

# Copy faxe application
COPY ./ faxe

WORKDIR faxe

# define all packeges that should be updated
#ARG update_list="libbsd* libzstd* libcurl3-gnutls libldap-common libopenjp2-7 python3.7  libtiff5 linux-libc-dev subversion libpq5 libldap-2.4-2 liblz4-1 libsvn1"
#ARG remove_list=""

# faxe extensions
ENV FAXE_EXTENSIONS="ext.config"
# build emqtt client without quic
ENV BUILD_WITHOUT_QUIC=true

# install git, build release and cleanup deps
RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ make git-all curl jq \
	#&& apt --only-upgrade --no-install-recommends install ${update_list} -y  \
    #&& apt remove  --auto-remove ${remove_list} -y  \
    && apt upgrade -y \
    && apt autoremove -y \
    # tell git to use https instead of git protocol (faxe dependencies)
    && git config --global url."https://".insteadOf git:// \
    && rebar3 as balena release \
    && apt-get purge -y --auto-remove gcc g++ make git-all \
    && rm -rf /var/lib/apt/lists/*

RUN  [ -d scripts ] && mv scripts/* _build/balena/rel/faxe ; ls -l _build/balena/rel/faxe

### Build stage 2
FROM erlang

# Install the released application
COPY --from=erlang /buildroot/faxe/_build/balena/rel/faxe /faxe
# cleanup
RUN rm -rf /buildroot

# Expose relevant ports
## http api
EXPOSE 80

ENTRYPOINT ["/faxe/bin/faxe", "foreground"]
#CMD ["foreground"]